name: Test run v1

on:
  workflow_dispatch:

jobs:
  env:
    runs-on: ubuntu-18.04
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: "root"
          MYSQL_DATABASE: "mysqldb"
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Show environment v1
        run: env | grep ^GITHUB

      - name: Try connect to db with docker
        run: |
          docker run --rm busybox nc -zv -w 3 mysql 3306
          docker run --rm busybox nc -zv -w 3 google.com 443
